In [1]:
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
for planet in planets:
    print(planet)

Mercury
Venus
Earth
Mars
Jupiter
Saturn
Uranus
Neptune
Pluto


In [2]:
print("but Pluto's not a planet, so let's try again.")
planets.pop()
print(planets)

but Pluto's not a planet, so let's try again.
['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


In [5]:
print("That's better. We can also: ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
planets.pop(8)
for i, planet in enumerate(planets):
    print(f'{i}.{planet}')

That's better. We can also: 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [7]:
print("Additionally: ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
for i, planet in enumerate(planets[:-1]):
    print(f'{i}.{planet}')

Additionally: 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [9]:
print("likewise: ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
for i, planet in enumerate(planets[:8]):
    print(f'{i}.{planet}')

likewise: 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [13]:
print("You're starting to get it. ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
for i, planet in enumerate(planets[-9:-1]):
    print(f'{i}.{planet}')

You're starting to get it. 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [14]:
print("Now let's try: ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
del(planets[8])
for i, planet in enumerate(planets):
    print(f'{i}.{planet}')

Now let's try: 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [16]:
print("similarly: ")
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
planets.remove('Pluto')
for i, planet in enumerate(planets):
    print(f'{i}.{planet}')

similarly: 
0.Mercury
1.Venus
2.Earth
3.Mars
4.Jupiter
5.Saturn
6.Uranus
7.Neptune


In [19]:
print("now that we've got our planets sorted, let's sort them alphabetically: ")
print("sorted: ",sorted(planets))
print("old list: ",planets)
print("note planets didn't get sorted - sorted returns a sorted (alphabetized in this case) list without sorting from any iterable")
print("to sort the original in place, we use sort()")
print("sorted: ",planets.sort()) # sort() returns type None, but sorts the array it is invoked upon.
print("planets after using sort: ", planets)

now that we've got our planets sorted, let's sort them alphabetically: 
sorted:  ['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']
old list:  ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
note planets didn't get sorted - sorted returns a sorted (alphabetized in this case) list without sorting from any iterable
to sort the original in place, we use sort()
sorted:  None
planets after using sort:  ['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']


In [20]:
len(planets)
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"][:-1]
distances_of_planets = [0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06]
for p, d in zip(planets, distances_of_planets):
    print(f'{p} is {d}AU from the Sun.')


Mercury is 0.39AU from the Sun.
Venus is 0.72AU from the Sun.
Earth is 1AU from the Sun.
Mars is 1.52AU from the Sun.
Jupiter is 5.2AU from the Sun.
Saturn is 9.54AU from the Sun.
Uranus is 19.2AU from the Sun.
Neptune is 30.06AU from the Sun.


In [26]:
planets.append('Pluto')
planets_plus_pluto = planets # cannot assign directly, append returns None, this copy is shallow.
distances_of_planets.append(49.3) 
planets.extend(distances_of_planets)
print(planets) 

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Pluto', 0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06, 49.3, 49.3, 49.3, 49.3, 49.3, 'Pluto', 0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06, 49.3, 49.3, 49.3, 49.3, 49.3, 49.3]


In [29]:
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"][:-1]
distances_of_planets = [0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06]
print(list(zip(planets, distances_of_planets)))

[('Mercury', 0.39), ('Venus', 0.72), ('Earth', 1), ('Mars', 1.52), ('Jupiter', 5.2), ('Saturn', 9.54), ('Uranus', 19.2), ('Neptune', 30.06)]


In [31]:
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"][:-1]
distances_of_planets = [0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06]
for p, d in list(zip(planets, distances_of_planets)):
    print(f'{p} is {d}AU from the Sun.')

Mercury is 0.39AU from the Sun.
Venus is 0.72AU from the Sun.
Earth is 1AU from the Sun.
Mars is 1.52AU from the Sun.
Jupiter is 5.2AU from the Sun.
Saturn is 9.54AU from the Sun.
Uranus is 19.2AU from the Sun.
Neptune is 30.06AU from the Sun.


In [34]:
planets_with_distances_iterable = zip(planets, distances_of_planets)
keep_going = True
while keep_going:
    try:
        temp = planets_with_distances_iterable.next()
        print(temp)
    except Exception as e:
        print('nope!',e) # fails because while zip is iterable, it doesn't implement next() like some.
        keep_going = False
print('done!')

too far! 'zip' object has no attribute 'next'
done!


In [35]:
# you can unzip what is zipped:
p, d = zip(*planets_with_distances_iterable) # note the unpacking operator.
print(p)
print(d)

('Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune')
(0.39, 0.72, 1, 1.52, 5.2, 9.54, 19.2, 30.06)


In [38]:
zippedlist = list(zip(p,d))
zippedlist.sort()
print(zippedlist) # alphabetical by planet name (sort sorts by first item zipped)
zippedlist = list(zip(d,p))
zippedlist.sort()
print(zippedlist) # by distance from the sun.
# this essentially let us sort on whatever column we like.

[('Earth', 1), ('Jupiter', 5.2), ('Mars', 1.52), ('Mercury', 0.39), ('Neptune', 30.06), ('Saturn', 9.54), ('Uranus', 19.2), ('Venus', 0.72)]
[(0.39, 'Mercury'), (0.72, 'Venus'), (1, 'Earth'), (1.52, 'Mars'), (5.2, 'Jupiter'), (9.54, 'Saturn'), (19.2, 'Uranus'), (30.06, 'Neptune')]


In [47]:
# sorting will also let you take for a key a lambda which accepts the item sorted over ( a tuple in this case with planet, distance) and run a lambda, letting you filter things.
# let's get all the planets with the letter 'e' in them before the others: 
zippedlist = list(zip(p,d))
zippedlist.sort(key=lambda p: 'e' not in p[0].lower()) # false is less than true, so we look for not in to get e's first.
done = False
for item in zippedlist:
    print(item)

('Mercury', 0.39)
('Venus', 0.72)
('Earth', 1)
('Jupiter', 5.2)
('Neptune', 30.06)
('Mars', 1.52)
('Saturn', 9.54)
('Uranus', 19.2)


In [56]:
planets_with_light_minutes = list(map(lambda p: (p[0], str(p[1]*8.32)+' light-minutes'), zippedlist))
for j,k in planets_with_light_minutes:
    print(j+":",k)

Mercury: 3.2448 light-minutes
Venus: 5.9904 light-minutes
Earth: 8.32 light-minutes
Jupiter: 43.264 light-minutes
Neptune: 250.0992 light-minutes
Mars: 12.6464 light-minutes
Saturn: 79.3728 light-minutes
Uranus: 159.744 light-minutes


In [63]:
import time
import numpy as np
# make two big arrays, then delete them in a loop by two differnet methods.
a = []
b = []
c = []
d = []
e = []
f = []
g = []
h = []
for i in range (2000):
    a.append(i)
    b.append(i)
    c.append(i)
    d.append(i)
    e.append(i)
    f.append(i)
    g.append(i)
    h.append(i)
start_time = time.time()
for i in range(2000):
    del(a[0])
print("---del: %s seconds ---" % (time.time() - start_time))
start_time = time.time()
for i in range(2000):
    b = b[1:]
print("---assign slice: %s seconds ---" % (time.time() - start_time))
start_time = time.time()
for i in range(2000):
    del(c[:-1])
print("---del(end): %s seconds ---" % (time.time() - start_time))
start_time = time.time()
for i in range(2000):
    d.pop()
print("---pop(end): %s seconds ---" % (time.time() - start_time))
    

---del: 0.0003376007080078125 seconds ---
---slice: 0.00336456298828125 seconds ---
---del(end): 0.0006685256958007812 seconds ---
---pop(end): 0.00011277198791503906 seconds ---


# findings:
1. assigning a slice is marginally more efficient than del and matters when a million or more ops
2. popping the end is faster than deleting the end, and matters when ten thousand or more ops
3. del is slow for big loops.
   Curious about differences between numpy arrays and python arrays, I googled, found on reddit the following nice summary:"
 * Python array:
   - the term is "Python list"
   - usage: everyday plain Python code
 * NumPy array:
    - data manipulation that needs to be fast
    - can use Python lists if speed isn't a concern
    - supports fast and convenient vectorized functions: write np.sqrt(array) instead of [math.sqrt(number) for number in your_list]
    - elegantly handles arbitrary number of dimensions
 * Pandas dataframe:
     - for data wrangling in SQL-like language
     - similar to in-memory SQLite database
     - supports NumPy's vectorized functions
     - basically a glorified NumPy array with column names
" -- credit ForceBru



In [7]:
import numpy as np
ar = np.array([1,3,5,7,9])
print(ar)
print(np.__version__)
ar_fns = []
for fn in dir(ar):
    if not '__' in fn:
        ar_fns.append(fn)
print(ar_fns)
print(type(ar))

[1 3 5 7 9]
2.1.3
['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'device', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'mT', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'to_device', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']
<class 'numpy.ndarray'>


In [59]:
# 0d
ar0 = np.array(42)
#1d 
ar1 = np.array([1,2,3,4])
#2d
ar2 = np.array([[1,2,3],[4,5,6]])
#3d
ar3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('---0d---')
print(ar0)
print('---1d---')
for el in ar1:
    print(el, end='')
print('')
print('--2d----')
for line in ar2:
    for el in line:
        print(el, end='')
    print('')
print('--3d----')
for layer, z in enumerate(ar3):
    print('z'+str(layer)+':')
    print('',end='\t   ')
    for k in range(0, 2):
        print('y'+str(k), end=' ')
    print('')
    for line, x in enumerate(z):
        print('\tx'+str(line)+':'+str(x))
    

---0d---
42
---1d---
1234
--2d----
123
456
--3d----
z0:
	   y0 y1 
	x0:[1 2]
	x1:[3 4]
z1:
	   y0 y1 
	x0:[5 6]
	x1:[7 8]


In [65]:
print("ndim attribute provides the number of dimensions of an array")
ar4 = np.array([ar3, ar3]) #  hypercube with sides of length 2
ar5 = np.array([ar4, ar4]) #  penteract with sides of length 2
print(ar0.ndim, ar1.ndim, ar2.ndim, ar3.ndim, ar4.ndim, ar5.ndim)
print('a 5d cube is known as a penteract.')

ndim attribute provides the number of dimensions of an array
0 1 2 3 4 5
a 5d cube is known as a penteract.


In [71]:
print("You can specify the number of dimensions for an array when creating it using ndmin arg like np.array([1,2,3,4], ndmin=6)")
ar6 = np.array([1,2,3,4], ndmin=6)
print(ar6)
print("Note that it doesn't fill out the array - just 'embeds' what you give it in that 'space'.")
print("Dimensions: ", ar6.ndim)
print("but it does now show as having that many dimensions")


You can specify the number of dimensions for an array when creating it using ndmin arg like np.array([1,2,3,4], ndmin=6)
[[[[[[1 2 3 4]]]]]]
Note that it doesn't fill out the array - just 'embeds' what you give it in that 'space'.
Dimensions:  6
but it does now show as having that many dimensions


In [76]:
print("You can also provide a dtype argument, like np.array([1,2,3,4], dtype='int')")
janet = np.array([1,2,3,4], dtype='int') # valid
print("Array janet: ",janet)
try:
    mark = np.array([1,2,3,'a'], dtype='int') #breaks
except ValueError:
    print("when I try and create mark, it breaks with a value error like this.")

You can also provide a dtype argument, like np.array([1,2,3,4], dtype='int')
Array janet:  [1 2 3 4]
when I try and create mark, it breaks with a value error like this.


numpy data types:
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [79]:
arr = np.array([1.1, 2.1, 3.1])

print("You can cast a numpy array with astype if it can be converted.")
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

You can cast a numpy array with astype if it can be converted.
[1 2 3]
int32
[ True False  True]
bool


In [82]:
print("""
a copy makes a copy, a view accesses the original:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
y[1] = 8
print(arr, x, y)
print(x.base) # returns none if the obj owns it's data
print(y.base) # returns original obj otherwise
results:
""")
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
y[1] = 8
print(arr, x, y)
print("x base: ",x.base)
print("y base: ",y.base)


a copy makes a copy, a view accesses the original:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
y[1] = 8
print(arr, x, y)
print(x.base) # returns none if the obj owns it's data
print(y.base) # returns original obj otherwise
results:

[42  8  3  4  5] [1 2 3 4 5] [42  8  3  4  5]
x base:  None
y base:  [42  8  3  4  5]


In [85]:
print("""
shape gives an array with the lengths of the dimensions of an array: 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]])
print(arr2.shape)
""")
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr2.shape)


shape gives an array with the lengths of the dimensions of an array: 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]])
print(arr2.shape)

(2, 4)
(2, 2, 2)


In [86]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [87]:
print("self explanatory: ")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])")
newarr = arr.reshape(4, 3)
print("newarr = arr.reshape(4,3)")
print(newarr)
print("arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("newarr = arr.reshape(2, 3, 2)")
newarr = arr.reshape(2, 3, 2)
print(newarr)


self explanatory: 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [88]:
try:
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
    newarr = arr.reshape(3, 3)
    print(newarr)
except ValueError:
    print("""You can't reshape an array to an array that has the wrong number of elements, 
    it throws a value error.""")


You can't reshape an array to an array that has the wrong number of elements, 
    it throws a value error.


In [91]:
print("""
A reshaped array is just a view of the original.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = arr.reshape(2, 4)
print(arr2)
print(arr2.base)
arr2[0] = 4
print(arr)
arr[0] = 1
print(arr)
print(arr2)
""")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = arr.reshape(2, 4)
print(arr2)
print(arr2.base)
arr2[0] = 4
print(arr)
arr[0] = 1
print(arr)
print(arr2)


A reshaped array is just a view of the original.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = arr.reshape(2, 4)
print(arr2)
print(arr2.base)
arr2[0] = 4
print(arr)
arr[0] = 1
print(arr)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[4 4 4 4 5 6 7 8]
[1 4 4 4 5 6 7 8]
[[1 4 4 4]
 [5 6 7 8]]


In [92]:
arr = [[1,2,3,4],[5,6,7,8]]
arr[0] = 3
print(arr)

[3, [5, 6, 7, 8]]


In [94]:
print("""
nditer is a numpy helper function which lets you print out 
every item in a high dimensional array without nested loops.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)
""")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)


nditer is a numpy helper function which lets you print out 
every item in a high dimensional array without nested loops.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [102]:
arr = np.array([1, 2, 3, 0, -1, 10, 2])
# the 'buffered' flag creates a memory space to convert datatypes while iterating
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
try:
  for x in np.nditer(arr, flags=['buffered'], op_dtypes=['bool']):
    print(x)
except TypeError:
    print("You can't cast from int to bool with nditer, it's a bit more typesafe.")
print("You can manually cast them like this though: ")
for x in np.nditer(arr):
   print(bool(x))

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'0')
np.bytes_(b'-1')
np.bytes_(b'10')
np.bytes_(b'2')
You can't cast from int to bool with nditer, it's a bit more typesafe.
You can manually cast them like this though: 
True
True
True
False
True
True
True


In [104]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("iterate over every other element, converting all to strings")
for x in np.nditer(arr[:, ::2], flags=['buffered'], op_dtypes=['S']):
  print(x)

iterate over every other element, converting all to strings
np.bytes_(b'1')
np.bytes_(b'3')
np.bytes_(b'5')
np.bytes_(b'7')


In [105]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [110]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print("numpy's concatenate function combines two numpy ndarrays")
print(type(arr))

numpy's concatenate function combines two numpy ndarrays
<class 'numpy.ndarray'>


In [118]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.concatenate((arr1, arr2), axis=0)
arr4 = np.concatenate((arr1, arr2), axis=1)
arr6 = np.array(arr1, ndmin=3)
arr7 = np.array(arr2, ndmin=3)
print(arr3)
print(arr4)
print(arr6)
print(arr7)
arr8 = np.concatenate((arr6,arr7), axis=2)
print()
print(arr8)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]]
[[[5 6]
  [7 8]]]

[[[1 2 5 6]
  [3 4 7 8]]]


In [129]:
print("""
Stacking is same as concatenation, the only difference is 
that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which 
would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() 
method along with the axis. If axis is not explicitly passed it is taken as 0.
""")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
arr3 = np.stack((arr1, arr2), axis=0)
arr4 = arr3.reshape(3,1,2)
arr5 = np.stack((arr4, arr4), axis=2)
print(arr,'\n------------------\n',arr3,'\n------------------\n',arr4,'\n------------------\n',arr5)
print(arr5.ndim)


Stacking is same as concatenation, the only difference is 
that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which 
would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() 
method along with the axis. If axis is not explicitly passed it is taken as 0.

[[1 4]
 [2 5]
 [3 6]] 
------------------
 [[1 2 3]
 [4 5 6]] 
------------------
 [[[1 2]]

 [[3 4]]

 [[5 6]]] 
------------------
 [[[[1 2]
   [1 2]]]


 [[[3 4]
   [3 4]]]


 [[[5 6]
   [5 6]]]]
4


In [131]:
print("""numpy provides some convenience functions for stacking along x and y: vstack and dstack
They are identical to picking axis 0 and axis 1, respectively.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
arr3 = np.stack((arr1, arr2), axis=0)
arr4 = np.dstack((arr1, arr2))
arr5 = np.stack((arr1, arr2), axis=1)
print(arr)
print(arr3)
print(arr4)
print(arr5)
""")
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
arr3 = np.stack((arr1, arr2), axis=0)
arr4 = np.dstack((arr1, arr2))
arr5 = np.stack((arr1, arr2), axis=1)
print(arr)
print(arr3)
print(arr4)
print(arr5)

numpy provides some convenience functions for stacking along x and y: vstack and dstack
They are identical to picking axis 0 and axis 1, respectively.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
arr3 = np.stack((arr1, arr2), axis=0)
arr4 = np.dstack((arr1, arr2))
arr5 = np.stack((arr1, arr2), axis=1)
print(arr)
print(arr3)
print(arr4)
print(arr5)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[[1 4]
 [2 5]
 [3 6]]


In [139]:
print("""arr = np.array([1,3,5,7,7,7,9,11,13,15])
print(arr.searchsorted(5)) # returns the first position where 5 should be inserted to maintain sort order.
print(arr.searchsorted(7, side='right')) # returns the first position where 6 should be inserted to maintain sort order, searching from the right
print(arr.searchsorted(7)) # and the normal way to compare
print(arr.searchsorted([7,9,15]) # you can search for more than one value.
print(arr.searchsorted([7,9,15], side='right')) # you can search for more than one value from the right
""")
arr = np.array([1,3,5,7,7,7,9,11,13,15])
print(arr.searchsorted(5)) # returns the first position where 5 should be inserted to maintain sort order.
print(arr.searchsorted(7, side='right')) # returns the first position where 6 should be inserted to maintain sort order, searching from the right
print(arr.searchsorted(7)) # and the normal way to compare
print(arr.searchsorted([7,9,15])) # you can search for more than one value.
print(arr.searchsorted([7,9,15], side='right')) # you can search for more than one value from the right

arr = np.array([1,3,5,7,7,7,9,11,13,15])
print(arr.searchsorted(5)) # returns the first position where 5 should be inserted to maintain sort order.
print(arr.searchsorted(7, side='right')) # returns the first position where 6 should be inserted to maintain sort order, searching from the right
print(arr.searchsorted(7)) # and the normal way to compare
print(arr.searchsorted([7,9,15]) # you can search for more than one value.
print(arr.searchsorted([7,9,15], side='right')) # you can search for more than one value from the right

2
6
3
[3 6 9]
[ 6  7 10]


In [143]:
print("""
arr = np.array([41, 42, 43, 44])

filtered = arr[[True, False, True, True]]
filtered2 = arr[arr > 42]
print(filtered, filtered2)
# np lets you filter on array by a boolean filter 
# values set to false are excluded. a smaller array is returned of just
# those values which had a corresponding 'true' in the boolean filter
# typically this filter is made on the fly via some function
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)
""")
arr = np.array([41, 42, 43, 44])

filtered = arr[[True, False, True, True]]
filtered2 = arr[arr > 42]
print(filtered, filtered2)
# np lets you filter on array by a boolean filter 
# values set to false are excluded. a smaller array is returned of just
# those values which had a corresponding 'true' in the boolean filter
# typically this filter is made on the fly via some function
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


arr = np.array([41, 42, 43, 44])

filtered = arr[[True, False, True, True]]
filtered2 = arr[arr > 42]
print(filtered, filtered2)
# np lets you filter on array by a boolean filter 
# values set to false are excluded. a smaller array is returned of just
# those values which had a corresponding 'true' in the boolean filter
# typically this filter is made on the fly via some function
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43 44] [43 44]
[False, True, False, True, False, True, False]
[2 4 6]


In [153]:
from numpy import random

arr = random.randint(100, size=(3,4))
print(arr)
arr = random.rand(2,1,1,1,1,1) # 6 dimensional array, with 2 numbers along one axis
print(arr)

arr = arr.reshape(2) # reduce to 2d array
print(arr)
arr = np.array(arr, ndmin=6)
print(arr.reshape(2,1,1,1,1,1)) # embedded back into 6d space.

[[45 39 10 98]
 [16 55 12 35]
 [22 85 92 42]]
[[[[[[0.32380218]]]]]




 [[[[[0.02391214]]]]]]
[0.32380218 0.02391214]
[[[[[[0.32380218]]]]]




 [[[[[0.02391214]]]]]]
